#!/bin/sh

common_install()
{
   cp .bash_profile ~
   cp .bashrc ~
   cp .gvimrc ~
   cp .inputrc ~
   cp .profile ~
   cp .vimrc ~
}

Darwin_install()
{
   common_install
   cp macosx/.gitconfig ~
   cp .fonts/* ~/Library/Fonts
   cp -R .vim ~
}

$(uname)_install
