#!/bin/bash

common_install()
{
   cp .bash_profile ~
   cp .bashrc ~
   cp .gvimrc ~
   cp .inputrc ~
   cp .profile ~
   cp .vimrc ~
}

cygwin_install()
{
   common_install
   # The .gitconfig is incomplete, so its contents should be manually merged
   # into ~/.gitconfig
   #cp windows/.gitconfig ~
   cscript.exe windows/install_fonts.vbs
   mkdir -p ~/vimfiles
   cp -R .vim/* ~/vimfiles
}

darwin_install()
{
   common_install
   # The .gitconfig is incomplete, so its contents should be manually merged
   # into ~/.gitconfig
   #cp macosx/.gitconfig ~
   cp .fonts/* ~/Library/Fonts
   cp -R .vim ~
}

# Call the OS-specific install function.  On Mac OS X the OSTYPE ends with a
# number that signifies the darwin release number, so strip that off.
${OSTYPE//[0-9.]}_install
